
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Opens the folder picker and adopts the chosen directory as the workspace.
 * 
 * The dialog is opened here rather than in the web layer on purpose. When the
 * frontend picks the folder and then hands the path back, the path is the
 * untrusted side's to choose, and the confinement below it — however carefully
 * built — only ever confines access to a root an attacker could have named.
 * Owning the picker is what makes the root the user's choice, and it lets the
 * webview drop the dialog capability entirely.
 */
async chooseWorkspace() : Promise<Result<string | null, DesktopError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("choose_workspace") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The workspace already adopted, if there is one.
 * 
 * A root can be adopted before the interface exists — the startup path
 * argument does exactly that — and re-asking the user to pick a folder they
 * already named would be wrong. It returns a path but cannot set one.
 */
async currentWorkspace() : Promise<Result<string | null, DesktopError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("current_workspace") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDocuments() : Promise<Result<DocumentRow[], DesktopError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_documents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readDocument(id: string) : Promise<Result<string, DesktopError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_document", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeDocument(id: string, contents: string) : Promise<Result<FileMetadata, DesktopError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_document", { id, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createDocument(path: string, contents: string) : Promise<Result<DocumentRow, DesktopError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_document", { path, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameDocument(id: string, path: string) : Promise<Result<null, DesktopError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_document", { id, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeDocument(id: string) : Promise<Result<null, DesktopError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_document", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startWorkspaceWatch() : Promise<Result<null, DesktopError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_workspace_watch") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/

export const EXTERNAL_CHANGE_EVENT = "workspace://external-change" as const;

/** user-defined types **/

export type DesktopError = 
/**
 * The path escapes the workspace, or is not a path this application will
 * accept. Refused before anything touches the filesystem.
 */
{ kind: "outside-workspace"; path: string } | 
/**
 * No document with that identifier.
 */
{ kind: "not-found" } | 
/**
 * The file changed since it was last read, so writing would discard
 * somebody else's work.
 */
{ kind: "changed-underneath" } | 
/**
 * Anything not worth a category of its own. The message is for a log, not
 * for a caller to parse.
 */
{ kind: "unexpected"; message: string }
export type DocumentRow = { id: string; path: string; sha256: string | null; mtimeUnixMs: number | null }
export type FileMetadata = { path: string; sha256: string; mtimeUnixMs: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
